# Generated by Django 3.2.9 on 2021-12-15 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0002_iteganyagihe'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Idafarmuser',
            new_name='Bankaccount',
        ),
        migrations.RenameModel(
            old_name='Iteganyagihe',
            new_name='Bankdetails',
        ),
    ]
