# Generated by Django 3.2.9 on 2021-12-15 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0005_rename_sizeofland_bankaccount_locationofbank'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankaccount',
            old_name='names',
            new_name='customerName',
        ),
    ]
