# Generated by Django 3.2.9 on 2021-12-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ussd', '0006_rename_names_bankaccount_customername'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='balance',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
    ]
